@api= http://localhost:8000/api
@path= checkout
### GET ALL DATA
GET {{api}}/{{path}}


### GET ID DATA
GET {{api}}/{{path}}/4

### CREATE DATA
POST {{api}}/{{path}}
Content-Type: application/json

{
    "id_user": 1,
    "total": 200,
    "delivery_price": 23,
    "payment_price": 23,
    "payment_method": "mandiri",
    "delivery_method": "jnt"
}

### UPDATE DATA
PUT {{api}}/{{path}}/1
Content-Type: application/json

{
    "id_user": 1,
    "total": 200,
    "delivery_price": 23,
    "payment_price": 23,
    "payment_method": "mandiri update",
    "delivery_method": "jnt"
}
### DELETE DATA
DELETE {{api}}/{{path}}/4

