@api= http://localhost:8000/api
@path=favorite

### GET ALL DATA
GET {{api}}/{{path}}

### GET ID DATA BY USER ID
GET {{api}}/{{path}}/id-user/14

### GET ID DATA BY USER ID
GET {{api}}/{{path}}/id-list/13


### GET ID DATA
GET {{api}}/{{path}}/4

### CREATE DATA
POST {{api}}/{{path}}
Content-Type: application/json

{
    "id_user": 14,
    "title": "animal",
    "description": "is animal art"
}

### //   "id_product": 2,
### CREATE DATA
PUT {{api}}/{{path}}/14
Content-Type: application/json

{
    "id_user": "1",
    "title": "animal",
    "description": "is animal art"
}

###//    "id_product": "2",
### DELETE DATA
DELETE {{api}}/{{path}}/4

