@api= http://localhost:8000/api
@path= product

### GET ALL DATA
GET {{api}}/{{path}}

### GET ID DATA
GET {{api}}/{{path}}/1

### CREATE DATA
POST {{api}}/{{path}}
Content-Type: application/json

{
    "name": "test buku",
    "qty": 1,
    "price": 123,
    "id_user": 1,
    "description": "s simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry"

}

### UPDATE DATA
PUT {{api}}/{{path}}/4
Content-Type: application/json

{
    "name": "test buku update",
    "qty": 1,
    "price": 123,
    "id_user": 1,
    "description": "s simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry"

}

### DELETE DATA
DELETE {{api}}/{{path}}/1

