@api= http://localhost:8000/api
@path = trolley

### GET ALL DATA
GET {{api}}/{{path}}
Content-Type: application/json

### GET ID DATA
GET {{api}}/{{path}}/4
Content-Type: application/json


### GET USER BY ID DATA
GET {{api}}/{{path}}/id-user/14
Content-Type: application/json

### GET USER BY ID DATA
GET {{api}}/{{path}}/id-checkout/103
Content-Type: application/json



### GET USER BY ID DATA
GET {{api}}/{{path}}/id-user/count/1
Content-Type: application/json


### CREATE DATA
POST {{api}}/{{path}}
Content-Type: application/json

{
    "qty": 1,
    "id_product": 30,
    "id_user": 13,
    "type": "90 ML"
}

### UPDATE DATA
PUT {{api}}/{{path}}/null
Content-Type: application/json

{
    "qty": 123,
    "id_product": 2,
    "id_user": 1
}

### //    "id_checkout": null,
### DELETE DATA
DELETE {{api}}/{{path}}/3

