@api= http://localhost:8000/api
@path= auth
### GET ALL DATA
POST {{api}}//tokens/create

### GET ALL DATA
GET {{api}}/{{path}}/user

### REGISTER DATA
POST {{api}}/{{path}}/register
Content-Type: application/json

{
    "name": "user19",
    "email": "user19@gmail.com",
    "password": "user12345",
    "password_confirmation": "user12345"
}

### UPDATE DATA
POST {{api}}/{{path}}/login
Content-Type: application/json

{
    "email": "user1@gmail.com",
    "password": "user12345"
}


### DELETE DATA
DELETE {{api}}/{{path}}/4

