@api= http://localhost:8000/api
@path= auth
### GET ALL DATA
POST {{api}}//tokens/create

### GET ALL DATA
GET {{api}}/{{path}}/user

### GET ALL DATA
GET {{api}}/{{path}}/user
Authorization: Bearer 10|UHrbz2u9P0vYjhZKSzbNQ09Lo1wXt0HkTVvDTXbN05199822


### REGISTER DATA
POST {{api}}/{{path}}/register
Content-Type: application/json

{
    "name": "user29",
    "email": "user29@gmail.com",
    "password": "user12345",
    "password_confirmation": "user12345"
}

### LOGIN DATA
POST {{api}}/{{path}}/login
Content-Type: application/json

{
    "email": "user29@gmail.com",
    "password": "user12345"
}


### GET ALL DATA
GET {{api}}/{{path}}/user
Authorization: Bearer 12|NHbLwb95RsFoTqLiAGFwoLB2QUjPcCJIJrdrKUXn7b5cc68e

### DELETE DATA
DELETE {{api}}/{{path}}/logout
Authorization: Bearer 11|vZJUjaTWpjtL5qIfAKBe8MTMIWZA5yiYlnUGxMp9c09513f3


